project:
  type: website

website:
  site-url: "https://rdm-os-cs-vu.github.io/open-handbook"
  title: "{{< var title >}}"
  description: "A place for all things open research at VU Amsterdam."
  favicon: public/favicon.png
  repo-url: https://github.com/rdm-os-cs-vu/open-handbook
  issue-url: https://github.com/rdm-os-cs-vu/open-handbook/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    background: "#0080c9"
    logo: public/VU-logo-Dia-positief.png
    logo-alt: "VU Amsterdam logo."
    # title: "Open Handbook"
    title: false
    collapse-below: lg
    left:
      - text: "Topics"
        menu:
          - text: All
            file: topics.qmd
          - text: Tools
            href: /topics.html#category=Tools
      - text: Guides
        file: guides.qmd
      - text: "CS RDM Guides"
        file: RDM-guidelines.qmd
      - text: "CS Groups"
        file: group-guidelines.qmd
      - text: "CS News"
        file: news.qmd
      - contributing.qmd
    tools:
      - icon: github
        href: https://github.com/rdm-os-cs-vu/open-handbook
        text: GitHub VU Open Handbook
      # - icon: rss
      #   href: https://quarto.org/docs/blog/index.xml
      #   text: Quarto Blog RSS
  page-footer:
    left:
      - text: "CC0 Public Domain Dedication"
        href: "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
    center:
      - text: "About"
        href: about.qmd
      - href: editors-guide.qmd
      - text: "GHOST Collective"
        href: https://ghostcollective.github.io/games.html
    right:
      - text: "By VU & Liberate Science GmbH"

bibliography: references.bib

resources:
  - "public/*"
  - CNAME
format:
  html:
    toc: true
    theme:
      - cosmo # https://bootswatch.com/
      - custom.scss # https://quarto.org/docs/output-formats/html-themes.html#theme-options
    code-copy: true
    code-overflow: wrap
# from: "markdown+emoji"
filters:
  - utils/include-files.lua
execute:
  freeze: auto
